export const GET_POSTS = 'GET_POSTS'
export const SET_SELECTED = 'SET_SELECTED'
export const REMOVE_POST = 'REMOVE_POST'
export const REMOVE_ALL_POSTS = 'REMOVE_ALL_POSTS'
export const SET_AS_READ = 'SET_AS_READ'